// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NobelPrizeWinners.Data;

namespace NobelPrizeWinners.Data.Migrations
{
    [DbContext(typeof(NobelPrizeWinnersDbContext))]
    partial class NobelPrizeWinnersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NobelPrizeWinners.Models.DataModels.NobelPrizeWinner", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BirthPlace");

                    b.Property<string>("Birthdate");

                    b.Property<string>("Category");

                    b.Property<string>("Country");

                    b.Property<string>("FieldOrLanguage");

                    b.Property<string>("Motivation");

                    b.Property<string>("Name");

                    b.Property<string>("PrizeName");

                    b.Property<string>("Residence");

                    b.Property<string>("Year");

                    b.HasKey("Id");

                    b.ToTable("NobelPrizeWinners");
                });
#pragma warning restore 612, 618
        }
    }
}
